# Generated by Django 5.2.9 on 2025-12-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Price', models.IntegerField()),
                ('Company', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
