# Generated by Django 5.2.9 on 2025-12-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcarddata',
            name='Image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
